replicaCount: 2

image:
  repository: houseprice-estimator
  pullPolicy: IfNotPresent
  tag: "v5"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30080

env:
  MODEL_PATH: "model/model.pkl"
  MLFLOW_TRACKING_URI: "sqlite:///mlflow-data/mlflow.db"
  PYTHONPATH: "/app"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
